name: Markdown Lint and Spell Check

on:
  pull_request:
    paths:
      - '**/*.md'

jobs:
  markdown-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install markdownlint-cli
        run: npm install -g markdownlint-cli

      - name: Run markdownlint
        run: markdownlint "**/*.md"

      - name: Install cspell (Code Spell Checker)
        run: npm install -g cspell

      - name: Run spell check with cspell
        run: cspell "**/*.md"
